name: Run PostgreSQL Scripts

on: 
  push:
    branches:
      - develop
    paths:
      - 'app/src/database/functions/*.sql'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PostgreSQL client
      run: sudo apt-get install -y postgresql-client

    - name: Identify changed SQL files and run them
      run: |
        changed_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
        for file in $changed_files
        do
          if [[ $file == src/database/functions/*.sql ]]
          then
            PGPASSWORD=${{ secrets.DB_PASSWORD }} psql --host ${{ secrets.DB_HOST }} --port ${{ secrets.DB_PORT }} --username ${{ secrets.DB_USER }} --dbname ${{ secrets.DB_NAME }} -f $file
          fi
        done
      env:
        DB_HOST: ${{ secrets.SUPABASE_DATABASE_HOST }}
        DB_PORT: ${{ secrets.SUPABASE_DATABASE_PORT }}
        DB_USER: ${{ secrets.SUPABASE_DATABASE_USER }}
        DB_NAME: ${{ secrets.SUPABASE_DATABASE_NAME }}
        DB_PASSWORD: ${{ secrets.SUPABASE_DATABASE_PASSWORD }}
